<a href="https://colab.research.google.com/github/saiganeshbollapinne143/AiAgent/blob/main/basicmlpytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch

In [ ]:
import torch
number=torch.tensor([1,2,3,4,5])
print(number)
print(type(number))
print(number.shape)

tensor([1, 2, 3, 4, 5])
<class 'torch.Tensor'>
torch.Size([5])


In [ ]:
import torch
table=torch.tensor([[1,2,3],
                    [4,5,6]])
print(table)
print(type(table))
print(table.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>
torch.Size([2, 3])


In [ ]:
zeroes=torch.zeros(2,3)
print(zeroes)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
random_matrix=torch.randn(3,3)
print(random_matrix)

tensor([[ 0.8734,  0.3161, -0.2719],
        [ 1.4756,  0.0234,  0.5912],
        [ 1.1176,  0.6076,  1.3013]])


In [ ]:
import torch.nn as nn
class SimpleModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer=nn.Linear(1,1)
  def forward(self,input_data):
    return self.layer(input_data)

In [ ]:
model=SimpleModel()
print(model)

SimpleModel(
  (layer): Linear(in_features=1, out_features=1, bias=True)
)


In [ ]:
print(model.named_parameters())

<generator object Module.named_parameters at 0x7cf2c3470540>


In [ ]:
for name,param in model.named_parameters():
  print(name,param)

layer.weight Parameter containing:
tensor([[0.1971]], requires_grad=True)
layer.bias Parameter containing:
tensor([-0.0305], requires_grad=True)


In [ ]:
#x=3y

In [ ]:
x_train=torch.tensor([[1.0],[2.0],[3.0],[4.0],[5.0]])
y_train=torch.tensor([[3.0],[6.0],[9.0],[12.0],[15.0]])

In [ ]:
#declaring model
model=SimpleModel()
#loss function MSE value(mean squared error)
loss_fn=nn.MSELoss()
#declaring an optimizer
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)

In [50]:
for epoch in range(5000):
    # forward pass
    prediction = model(x_train)
    # calculate loss
    loss = loss_fn(prediction, y_train)
    # backward pass
    loss.backward()
    # update weights
    optimizer.step()
    # clear the gradients
    optimizer.zero_grad()

    if (epoch+1) % 50 == 0:
      print(f'Epoch {epoch+1},Loss:{loss.item()}.3f')


Epoch 50,Loss:1.6370904631912708e-11.3f
Epoch 100,Loss:1.6370904631912708e-11.3f
Epoch 150,Loss:1.6370904631912708e-11.3f
Epoch 200,Loss:1.6370904631912708e-11.3f
Epoch 250,Loss:1.6370904631912708e-11.3f
Epoch 300,Loss:1.6370904631912708e-11.3f
Epoch 350,Loss:1.6370904631912708e-11.3f
Epoch 400,Loss:1.6370904631912708e-11.3f
Epoch 450,Loss:1.6370904631912708e-11.3f
Epoch 500,Loss:1.6370904631912708e-11.3f
Epoch 550,Loss:1.6370904631912708e-11.3f
Epoch 600,Loss:1.6370904631912708e-11.3f
Epoch 650,Loss:1.6370904631912708e-11.3f
Epoch 700,Loss:1.6370904631912708e-11.3f
Epoch 750,Loss:1.6370904631912708e-11.3f
Epoch 800,Loss:1.6370904631912708e-11.3f
Epoch 850,Loss:1.6370904631912708e-11.3f
Epoch 900,Loss:1.6370904631912708e-11.3f
Epoch 950,Loss:1.6370904631912708e-11.3f
Epoch 1000,Loss:1.6370904631912708e-11.3f
Epoch 1050,Loss:1.6370904631912708e-11.3f
Epoch 1100,Loss:1.6370904631912708e-11.3f
Epoch 1150,Loss:1.6370904631912708e-11.3f
Epoch 1200,Loss:1.6370904631912708e-11.3f
Epoch 1250,L

In [63]:
test_input=torch.tensor([81.0])
predection=model(test_input)
print(predection)

tensor([242.9998], grad_fn=<ViewBackward0>)
